#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Acceuil
index:
    path: /
    controller: App\Controller\AccueilController::index

#Se connecter compte visiteur
seConnecterVisiteur:
    path: /visiteur/connexion
    controller: App\Controller\VisiteurController::seConnecterVisiteur

#Saisir fiche de Visiteur    
saisir:
    path: /visiteur/saisir
    controller: App\Controller\VisiteurController::saisir

#Se deconnecter compte visiteur
seDeconnecterVisiteur:
    path: /visiteur/deconnexion
    controller: App\Controller\VisiteurController::seDeconnecter
 
#Choix du mois
choixMois:
    path: /visiteur/consulter
    controller: App\Controller\VisiteurController::choixMois

#Consulter
consulter:
    path: /visiteur/consulter
    controller: App\Controller\VisiteurController::consulter

#Modifier mot de passe
modifierMdp:
    path: /visiteur/modifierMdp
    controller: App\Controller\VisiteurController::modifierMdp

#Modifier données Personnelles
personnelles:
    path: /visiteur/personnelles
    controller: App\Controller\VisiteurController::personnelles
    
#Se connecter au compte comptable   
#seConnecterC:
#    path: /comptable/Connexion
#    controller: App\Controller\ComptableController::seConnecterC
    
#Menu comptable  
CompteComptable:
    path: /comptable/compte
    controller: App\Controller\ComptableController::comptable