#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Acceuil
index:
    path: /
    controller: App\Controller\AccueilController::index

#Se connecter compte visiteur
seConnecterVisiteur:
    path: /visiteur/connexion
    controller: App\Controller\VisiteurController::seConnecterVisiteur

#Se deconnecter compte visiteur
seDeconnecterVisiteur:
    path: /visiteur/deconnexion
    controller: App\Controller\VisiteurController::seDeconnecterVisiteur

#Menu visiteur   
CompteVisiteur:
    path: /visiteur/compte
    controller: App\Controller\VisiteurController::visiteur
    
#Choix du mois
choixMois:
    path: /visiteur/choixMois
    controller: App\Controller\VisiteurController::choixMois

#Consulter
consulter:
    path: /visiteur/consulter
    controller: App\Controller\VisiteurController::consulter
    
#Saisir fiche de Visiteur    
saisir:
    path: /visiteur/saisir
    controller: App\Controller\VisiteurController::saisir
    
#Se connecter au compte comptable   
#seConnecterC:
#    path: /comptable/Connexion
#    controller: App\Controller\ComptableController::seConnecterC
    
#Menu comptable  
CompteComptable:
    path: /comptable/compte
    controller: App\Controller\ComptableController::comptable