<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2dBpO5o\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2dBpO5o/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2dBpO5o.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2dBpO5o\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2dBpO5o\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2dBpO5o',
    'container.build_id' => 'de7ba897',
    'container.build_time' => 1616078603,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2dBpO5o');
