<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGACKXi5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGACKXi5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGACKXi5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGACKXi5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGACKXi5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GACKXi5',
    'container.build_id' => '5eefce29',
    'container.build_time' => 1619807821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGACKXi5');
