<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], []],
    'seConnecterVisiteur' => [[], ['_controller' => 'App\\Controller\\VisiteurController::seConnecterVisiteur'], [], [['text', '/visiteur/connexion']], [], []],
    'saisir' => [[], ['_controller' => 'App\\Controller\\VisiteurController::saisir'], [], [['text', '/visiteur/saisir']], [], []],
    'seDeconnecterVisiteur' => [[], ['_controller' => 'App\\Controller\\VisiteurController::seDeconnecter'], [], [['text', '/visiteur/deconnexion']], [], []],
    'choixMois' => [[], ['_controller' => 'App\\Controller\\VisiteurController::choixMois'], [], [['text', '/visiteur/consulter']], [], []],
    'consulter' => [[], ['_controller' => 'App\\Controller\\VisiteurController::consulter'], [], [['text', '/visiteur/consulter']], [], []],
    'modifierMdp' => [[], ['_controller' => 'App\\Controller\\VisiteurController::modifierMdp'], [], [['text', '/visiteur/modifierMdp']], [], []],
    'personnelles' => [[], ['_controller' => 'App\\Controller\\VisiteurController::personnelles'], [], [['text', '/visiteur/personnelles']], [], []],
    'CompteComptable' => [[], ['_controller' => 'App\\Controller\\ComptableController::comptable'], [], [['text', '/comptable/compte']], [], []],
];
